spring.application.name=cinema-booking
spring.data.mongodb.uri=mongodb://localhost:27017
logging.level.org.springframework.boot.autoconfigure.data.mongo=DEBUG
spring.data.mongodb.database=movies
server.port=8080

#logging.level.org.springframework=DEBUG

#logging.level.com.springboot_project=DEBUG
